// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using onlinePharmacy_Mvc.Data;

#nullable disable

namespace onlinePharmacy_Mvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240301041101_updateCreateProductTable")]
    partial class updateCreateProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("onlinePharmacy_Mvc.Models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuantityInStock")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("8a6708d3-882a-4b86-9601-7454c0c62990"),
                            Brand = "Opella Healthcare",
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/aspdotnet-c24e2.appspot.com/o/onlinePharmacy%2Ftelfast-180mg-tablet-10s-strip.jpg?alt=media&token=3991f954-4063-4910-a221-490b2a0656fe",
                            Price = 17.989999999999998,
                            ProductCategory = "Medicine",
                            ProductDescription = "This medicine is for oral use only. Swallow this medication as a whole with water. Do not chew, crush or break it. It is better to take this medication at a fixed time each day if it is indicated for everyday use. Take one tablet of Telfast 180mg once a day, with a glass of water.",
                            ProductName = "Telfast 180mg Tablet 10s (strip)",
                            QuantityInStock = 22
                        },
                        new
                        {
                            ProductID = new Guid("f895cd06-3580-4b93-9ab8-cee21ec4b23e"),
                            Brand = "Blackmores",
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/aspdotnet-c24e2.appspot.com/o/onlinePharmacy%2FBlackmores%20Grape%20Seed%20Forte%2012000%20Tablet%2030s.jpg?alt=media&token=3a6899ec-dca2-45c8-9b54-a5a5ae32ed93",
                            Price = 95.5,
                            ProductCategory = "Supplement",
                            ProductDescription = "Blackmores Grape Seed Forte is a natural antioxidant that helps protect bodily cells from free radical damage. It contains a high concentration of flavonoids, which help prevent skin elastin from degradation and promote collagen health and development.",
                            ProductName = "Blackmores Grape Seed Forte 12000 Tablet 30s",
                            QuantityInStock = 16
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
