// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using onlinePharmacy_Mvc.Data;

#nullable disable

namespace onlinePharmacy_Mvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240229103226_seedProductTable")]
    partial class seedProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("onlinePharmacy_Mvc.Models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuantityInStock")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("15fa9514-c105-4ae3-b1b8-316114242d4e"),
                            Brand = "Opella Healthcare",
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/aspdotnet-c24e2.appspot.com/o/onlinePharmacy%2Ftelfast-180mg-tablet-10s-strip.jpg?alt=media&token=3991f954-4063-4910-a221-490b2a0656fe",
                            Price = 17.989999999999998,
                            ProductCategory = "Medicine",
                            ProductDescription = "This medicine is for oral use only. Swallow this medication as a whole with water. Do not chew, crush or break it. It is better to take this medication at a fixed time each day if it is indicated for everyday use. Take one tablet of Telfast 180mg once a day, with a glass of water.",
                            ProductName = "Telfast 180mg Tablet 10s (strip)",
                            QuantityInStock = 22
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
